networks:
  translator-network:
    driver: bridge

services:
  translatordb:
    image: postgres:16.8
    container_name: translatordb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - translator-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_translator
    depends_on:
      - translatordb
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - translator-network

  translatorapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translatorapi
    depends_on:
      - translatordb
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      EXPIRATION_TIME: ${EXPIRATION_TIME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/.secrets/credentials.json
    networks:
      - translator-network

volumes:
  pgdata: