spring:
  config:
    import: optional:env[.env]
  application:
    name: translatorapi
  datasource:
    url: jdbc:postgresql://localhost:5432/translatordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret-key: "uma-chave-secreta-aleatoria-super-segura-de-pelo-menos-32-caracteres"
    expiration-time: 86400000 # definimos um dia em milissegundos para a expiração do token
openai:
  api:
    key: ${OPENAI_API_KEY}
